### ISSUE TITLE
"BUG" Añadir control sobre la cantidad para apostar

### ISSUE THREAD

**Issue by rubenvigo** [rubenvigo/vvsTest#4]
La cantidad minima permitida para apostar debe ser mayor que 0.

**Comment by lauramcastro** [comment]
Si esta issue la habéis abierto como consecuencia de una prueba, poned la referencia a su código. Si no, indicad cómo surge (inspección de código, etc.). Usad la etiqueta "bug".

**Comment by fbellos** [comment]
controlado bug en el comit:
b1c10faca37b68668e20b0d17f229e93c4159cba
caso de prueba PR-UN-096
