### ISSUE TITLE
Organización de pruebas en ficheros

### ISSUE THREAD

**Issue by lauramcastro** [rubenvigo/vvsTest#7]
No deberíais tener todas las pruebas unitarias en una única clase. Cada clase de pruebas debería agrupar los casos que afectan a los métodos de una unidad concreta, y no mezclar en un mismo archivo pruebas unitarias de unidades diferentes.

**Comment by fbellos** [comment]
nueva organización en ficheros en enl comit:
3b7e6da0b764be686beab2d2bc3a75636c6af120
