### ISSUE TITLE
Bugs encontrados por checkstyle de whitespace	

### ISSUE THREAD

**Issue by rubenvigo** [rubenvigo/vvsTest#8]
FileTabCharacter	    55	 Error
GenericWhitespace	      7	 Error
MethodParamPad	      4	 Error
NoWhitespaceAfter      3	 Error
NoWhitespaceBefore    6	 Error
OperatorWrap            16	 Error
ParenPad	                    10	 Error
WhitespaceAfter	    50	 Error
WhitespaceAround	  368	 Error

**Comment by fbellos** [comment]
Tarea solucionada con el commit 832e1bb52e73727e92081ad5f2b7228e0f98563c
